language: node_js
services:
  - docker
node_js: node
dist: trusty
sudo: true
cache: yarn
before_install:
  - sudo apt-get update
  - sudo apt-get install heroku-toolbelt
script:
  - yarn run test --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: script
  script: bash imagepush
  on:
    branch: release
