language: node_js
services:
  - docker
node_js: node
dist: trusty
sudo: true
cache: yarn
before_install:
  - sudo apt-get update
script:
  - yarn run test --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: script
  script: bash imagepush $TRAVIS_TAG
  on:
    tags: true
    branch: release
notifications:
  webhooks:
    urls:
      - https://discordapp.com/api/webhooks/594672739617472525/SWWZQIFHVg8hUVCIiMpnWGU5YrAgvmKdKr1OIaoddHWDmKFL3Q7S3NrQbS8Xpq2l7J7A