language: node_js
services:
  - docker
node_js: node
dist: trusty
sudo: required
cache: yarn
before_install:
  - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - openssl aes-256-cbc -K $encrypted_bd0c21e377f6_key -iv $encrypted_bd0c21e377f6_iv
    -in auth_config.json.enc -out ./auth_config.json -d
  - sudo apt-get update
script:
  - yarn run test --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - './send.sh success $DISCORD_WEBHOOK'
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - './send.sh failure $DISCORD_WEBHOOK'
deploy:
  provider: script
  skip_cleanup: true
  script: bash imagepush $TRAVIS_TAG
  on:
    tags: true
    branch: release
