#!bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin bbp10-jiriki.cf:5000
docker build -t bbp-jiriki-frontend .
docker tag bbp-jiriki-frontend bbp10-jiriki.cf/bbp-jiriki-frontend:$1
docker push bbp10-jiriki.cf/bbp-jiriki-frontend:$1
