#!bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin bbp10-jiriki.cf
docker build -t bbp-jiriki-frontend .
docker tag bbp-jiriki-frontend bbp10-jiriki.cf/bbp-jiriki-frontend
docker push bbp10-jiriki.cf/bbp-jiriki-frontend